<?php
/* @var $this yii\web\View */
?>
<h1>Informações Úteis</h1>
<h3>Terceirização</h3>
<p class="first justify">Por: Vilson Antonio Rodrigues Bilhalva.</p>
<h6>Ex-Juiz Presidente do TRT da 4ª  Região, professor de Direito do 
    Trabalho da PUC/RS, membro da Academia Nacional  de Direito do 
    Trabalho e Advogado (Rua Washington Luiz, 1.118, 9º andar,
    Porto  Alegre-RS - Fone/Fax: 221.5733 e 221.2019).</h6>

<p class="first justify">No plano do direito comparado, já em  1 º de março de 1848, a França abolia a "merchandage", sob argu&shy;mento  de que o trabalho, por não ser uma mercadoria, jamais poderia ser intermediado. </p>
<p class="first justify">Muito se discutiu e se confundiu  "merchandage" com terceirização. Num conceito atual, a terceirização  é a transferência da execução de determinadas atividades empresariais, até  então realizadas por pessoal próprio, para parceiros idôneos e especializados.  Quando se fala em terceirização, pensa-se numa grande empresa contratando  organizações de menor porte, porém o in&shy;verso também é verdadeiro. </p>
<p class="first justify">No plano do direito do trabalho o  que importa é a terceirização de serviços, que será comentada. </p>
<p class="first justify">Devido ao crescente índice de  desemprego, decor&shy;rente do êxodo rural, dos avanços tecnológicos - tele&shy;fonia,  informática, robótica - da globalização de merca&shy;dos e da transição econômica  que passa o país, admi&shy;te o nosso direito do trabalho a terceirização de servi&shy;ços  de dois tipos: temporários e permanentes, estes especializados, nas hipóteses e  condições legalmente previstas. </p>
<p class="first justify">A terceirização é alternativa de flexibilização empre&shy;sarial. </p>
<p class="first justify">Na terceirização de serviços  temporários a empresa tomadora importa mão-de-obra tratando-a como um es&shy;tepe  de seus recursos humanos, de empresas criadas para tal fim, com licenças  especiais. </p>
<p class="first justify">Na terceirização de serviços  permanentes especiali&shy;zados, a empresa contrata a execução de necessidade  específica. </p>
<p class="first justify">Ambos, temporários e permanentes especializados,  convivem na atualidade. No primeiro, contratam-se trab&shy;alhares através de  empresa interposta e, no segundo a prestação de serviços é realizada com  autonomia pela prestadora de serviços.</p>
<p class="first justify"> Nas últimas três décadas, o processo  de terceirização acentuou-se no Brasil, multiplicando o número de empresas cujo  objetivo é a oferta de mão-de-obra. A terceirização, em última análise, é a  execução indireta de tarefas, recebeu estímulo, explícito através do Decreto Lei  nº 200, de 25 de fevereiro de 1967, em seu capítulo 111, artigo 10 parágrafo 7º. </p>
<p class="first justify"> Eminentes doutrinadores passaram a  incluir na ter&shy;ceirização as mães sociais (Lei nº 7.644, de 18 de de&shy;zembro de  1987), as cooperativas de prestação de ser&shy;viços (Lei nº 8.949, de 9 de  dezembro de 1994, que acrescentou o parágrafo único ao artigo 442 da CLT) e a  “franchising” (Lei nº 8.955, de 15 de dezembro de 1994), embora não sejam  formas de terceirização, mas outras modalidades de negócios jurídicos, aliás,  em fran&shy;co desenvolvimento. </p>
<p class="first justify"> Na atual década, proliferam as  normas sobre tercei&shy;rização e a criação e contratação de empresas de pres&shy;tação  de serviços. </p>
<p class="first justify">Como bem salienta Maurício Godinho  Delgado. “A ordem jurídico-trabalhista inegavelmente deu legitimidade à  contratação de força de trabalho por interposta empresa, desde que autorizada  por lei especial.”</p>
<p class="first justify"> Conclui afirmando que, excluídas as  hipóteses le&shy;gais, "( ... ) não há, na ordem jurídica do país, preceito  legal a dar validade trabalhista a contratos mediante os quais uma pessoa  física preste serviços não-eventuais, onerosos, pessoais e subordinados a  outrem, serviços considerados essenciais à dinâmica  empresarial do to&shy;mador de serviços, sem que esse tomador responda,  juridicamente, pela relação laboral estabelecida."</p>
<p class="first justify">Dentre os defensores do fenômeno da  terceirização, destaca-se, modernamente, Jerônimo Souto Leiria que, tecendo  comentários sobre a conveniência do instituto, defende "(...) a <em>contratação  de terceiros </em>só <em>traz vanta&shy;gens. E- </em>o <em>que </em>é <em>fator importante </em>- <em>para ambos </em>os <em>lados da· nova parceria que </em>se <em>forma. Vale ressaltar que, no momento  atual,brasileiro, terceirizar </em>é <em>estratégi&shy;co,  oportuno </em>e <em>legal. E  estratégico, porque permite </em>a <em>concentração  de energia nas atividades-fim das empre&shy;sas, </em>com <em>ganhos adicionais pela  redução de custos ad&shy;ministrativos. E oportuno, porque </em>o <em>Judiciário  Trabalhis&shy;ta vem alterando seus conceitos, abandonando </em>a <em>priori&shy;dades </em>às <em>garantia  individuais </em>e <em>dirigindo-se para </em>os <em>ganhos coletivos. E legal, no  sentido de segurança de que </em>a <em>vontade  da empresa seja consagrada pela ótica judicial, desde que sejam tomados </em>os <em>devidos  cuidados nas contratações, </em>o <em>que </em>é <em>perfeitamente possível </em>e <em>de&shy;sejável". </em></p>
<p class="first justify">Em artigo publicado, o Ministro do  Tribunal Superior do Trabalho, Armando de Brito, sustenta: “A terceiriza&shy;ção,  idoneamente feita, constitui um avanço no campo da economia moderna, abrindo  espaço para um mais racional empenho por parte das empresas tomadoras em  aprimorar suas atividades finalistas". </p>
<p class="first justify"> O Tribunal Superior do Trabalho  editou dois enunci&shy;ados de jurisprudência uniforme sobre o tema: o Enun&shy;ciado  nº 256, revisto pelo Enunciado nº 331.</p>
<p class="first justify"> "Enunciado nº 256 -Contrato de  Prestação de Ser&shy;viços - Legalidade: Salvo os casos previstos nas Leis nºs  6.019, de 03.01.74 e 7.102, de 20.06.83, é ilegal a contratação de  trabalhadores por empresa interposta, formando-se o vínculo empregatício  diretamente com o Tomador&nbsp; de serviços”</p>
<p class="first justify">Enunciado nº 331: Contratação de  Prestação de Serviços – Legalidade – Revisão do Enunciado nº 256:</p>
<p class="first justify">I – A contratação&nbsp; de trabalhadores por empresa interposta é  legal, formando-se o vínculo diretamente com o tomador de serviços, saldo no  caso de trabalho temporário (Lei nº 6.019, de&nbsp;  03.01.74).</p>
<p class="first justify"> II – A contratação&nbsp; irregular de trabalhador, através da empresa &nbsp;interposta, não gera vínculo de emprego com os  órgãos da Administração Pública Direta, Indireta ou &shy;Fundações (Art. 37, 11, da Constituição da Repú&shy;blica). </p>
<p class="first justify"> III  - Não forma vínculo de emprego com o tomador a contratação de serviços  de vigilância (Lei nº 7.102, de 20.06.83), de conservação e limpeza, bem como a  de serviços especializados ligados à atividade-meio do to&shy;mador, desde que  inexistente a pessoal idade e a su&shy;bordinação direta. </p>
<p class="first justify"> IV- O inadimplemento das obrigações  trabalhistas, por parte do empregador, implica na responsabilidade subsidiária  do tomador dos serviços quanto àquelas obri&shy;gações, desde que este tenha  participado da relação processual e conste do título executivo judicial. (Res.  “OE nº 23, de 17.12.93 - DJU de 21.12.93).” </p>
<p class="first justify">O Enunciado nº 331 do Tribunal  Superior do Traba&shy;lho ampliou a possibilidade de utilização da terceiriza&shy;ção  de serviços temporários ou especializados perma&shy;nentes, estes desde que  inexistente pessoal idade ou subordinação direta, nas hipóteses legalmente  contem&shy;pladas, sem que implique na formação de vínculo de emprego dos  trabalhadores com as empresas tomadoras. </p>
<p class="first justify">- Temporários (Lei nº 6.019/74,  Decreto nº 73.841/ 74 e Enunciado 331, do TST). </p>
<p class="first justify">- Vigilância, segurança e transporte  de valores (Lei nº7.012/83, alterada pela Lei nº 8.863/94, Decreto nº 89.056/83  e Enunciado 331, 111, do TST). </p>
<p class="first justify"> - Conservação e limpeza (Enunciado  331, 111, do TST). </p>
<p class="first justify"> - Especializados ligados à  atividade-meio do toma&shy;dor (Enunciado 331, 111,  do TST).    </p>
<h5>TRABALHO TEMPORÁRIO</h5>
<p class="first justify">A Lei nº 6.019, de 3 de janeiro de  1974, publicada no DOU de 4 de janeiro de 1974, regulamentada pelo Decreto nº  73.841, de 13 de março de 1974, dispõe sobre o trabalho temporário nas empresas  urbanas, es&shy;tabelecendo, no artigo 2º, que 'trabalho temporário é aquele  prestado por pessoa física a uma empresa, para atender a necessidade  transitória de substituição de seu pessoal regular e permanente ou acréscimo  extraordi&shy;nário de serviços, desde que: (a) não excedente de três meses (art.1 O), (b) seja o contrato celebrado por escrito  (art.11); (c) através de empresa de trabalho emporário (art.3º).</p>
<p class="first justify">As empresas fornecedoras de trabalho  temporário registrarão na CTPS do trabalhador sua condição de temporário, pois  a transitoriedade é a característica essencial da prestação deste tipo serviço. <br>
    Segundo o artigo 26 do Decreto  73.841, para a prestação de serviço temporário é indispensável a celebra&shy;ção de  contrato escrito que as empresas fornecedoras e as empresas tomadoras de  trabalho temporário, dele devendo constar expressamente o motivo justificador  da demanda de trabalho temporário e a modalidade de remuneração da prestação de  serviço, onde estejam claramente discriminadas as parcelas relativas a salári&shy;os  e encargos sociais. </p>
<p class="first justify">A instrução Normativa nº 9, de 8 de  novembro de 1991, do Ministério do Trabalho, publicada no DOU de 14 de novembro  de 1991, estabelece, no artigo 1 º (a) nos incisos I e II, que o trabalho temporário só se ca&shy;racteriza  como tal quando destinado a atender a uma necessidade transitória das empresas  tomadoras, de&shy;corrente do afastamento ou impedimento de um em&shy;pregado  permanente por motivo de férias, auxílio-doen&shy;ça, licença-maternidade, etc. ou  a um acréscimo extra&shy;ordinário de serviço - pico de produção - das empre&shy;sas  tomadoras, (b) no § 1 º, que é vedada  a utilização de mão-de-obra temporária para atender a necessida&shy;de permanente,  através de contratos sucessivos com pessoas diferentes, para ocuparem a mesma  função nas empresas tomadoras; (c) no § 2º,  que constatada essa situação, o agente de inspeção do trabalho consi&shy;derará  descaracterizada a relação de trabalho temporá&shy;rio e configurado o vínculo  empregatício direto do tra&shy;balhador com as empresas tomadoras. </p>
<p class="first justify">Como sustenta Prunes: "Isto nos  leva a afirmar que o trabalho temporário (obedecidas as outras exigências  legais), é aquele de substituição de  empregados per&shy;manentes da empresa-cliente, como nos casos de féri&shy;as daqueles,  ou então outras interrupções ou suspen&shy;sões dos contratos de trabalho, qualquer  que seja a natureza dessas cessações momentâneas. Não se deve perder de vista a  duração máxima da substituição. Esta é a  situação mais "clássica", mais encontrada na práti&shy;ca". <br>
    A contratação de trabalhadores  temporários é permi&shy;tida, portanto, somente em situações excepcionais, com&shy;petindo  'B <em>Justiça do Trabalho dirimir </em>os <em>litígios entre </em>as <em>empresas  de serviço temporário e seus trabalhadores" </em>(art.19). </p>
<p class="first justify">Os conflitos entre as empresas  fornecedoras e to&shy;madoras de mão-de-obra são de competência da Justi&shy;ça Comum. </p>
<h5>VIGILÂNCIA, SEGURANÇA E TRANSPORTE DE VALORES</h5>
<p class="first justify">A Lei nº 7.102, de 20 de junho de  1983, dispõe so&shy;bre a segurança dos estabelecimentos financeiros e es&shy;tabelece  normas para constituição e funcionamento das empresas particulares especializadas  na exploração de serviços de vigilância, seguranças e transportes de va&shy;lores. <br>
    É regulamentado  pelo Decreto nº 89.056, de 24 de novembro de 1983, o qual, no artigo 53 ,  autoriza es&shy;sas empresas especializadas a prestarem serviços tam&shy;bém a  estabelecimentos não financeiros. <br>
    A especializa&shy;ção exigida é, pois,  dos trabalhadores e das empresas prestadoras de serviços de vigilância,  segurança e trans&shy;porte de valores. <br>
    As empresas tomadoras desses  serviços podem ser ou não estabelecimentos financeiros. </p>
<p class="first justify">O inciso  111, do Enunciado nº 331, do TST,  sintetiza a jurisprudência predominante sobre os conflitos traba&shy;lhistas  resultantes dessa atividade, reforçando o disposto no artigo 53 do Decreto nº  89.056/83 não gera vínculo de emprego com as empresas tomadoras a contrata&shy;ção  de serviços de vigilância, através de empresas cons&shy;tituídas na forma da Lei nº  7.102. </p>
<h5>CONSERVAÇÃO E LIMPEZA</h5>
<p class="first justify">A prestação de serviços de  conservação e limpeza, contratados através de empresas interpostas, desde que  inexistente pessoal idade ou subordinação, não configu&shy;ra vínculo de emprego  com a empresa tomadora, se&shy;gundo o inciso 111,  do Enunciado nº 331, do Tribunal Superior do Trabalho. Esta matéria é  ainda polêmica. </p>
<p class="first justify">Segundo Prunes: "Sobre este  tópico registram-se pa&shy;lavras candentes e até  agressivas, muitas das quais não merecem transcrição, eis que apenas revelam  pas&shy;sionalidade de seus autores e uma  visão unilateral de defesa de interesses. A realidade  é que os serviços de limpeza estão se  especializando de tal forma que os faxineiros 'internos', já se mostram  incapazes de traba&shy;lho a contento e em tempo satisfatório para o empresá&shy;rio.  Além disso, some-se também o horário em que tais serviços são prestados,  normalmente fora do expedien&shy;te normal das empresas."</p>
<h5>ATIVIDADE MEIO</h5>
<p class="first justify">Não forma vínculo de emprego com as  empresas tomadoras a contratação de serviços especializados para atender à  atividade-meio, desde que inexistente a pes&shy;soalidade e a subordinação direta  (Enunciado nº 331, III, do TST). </p>
<p class="first justify">Atividade-meio é a que serve de  suporte para as atividades-fim da empresa. <br>
    Nesta hipótese, abandona-se o critério  da atividade essencial, contínua ou de natureza permanente. <br>
    O diferencial a ser buscado é entre  a atividade-fim e a atividade-meio. </p>
<p class="first justify">Além disso, conecta-se o direito  comercial ao direito do trabalho. </p>
<p class="first justify">Através dos critérios do direito  comercial, analisa-se o contrato social, identificando se a empresa prestado&shy;ra  está habilitada à execução dos serviços. Prepondera a formalidade: a  verificação da habilitação. </p>
<p class="first justify">Segundo as normas do direito do  trabalho, examinam-se os serviços prestados, verificando se realmente são  especializados. Prepondera a informal idade: a verifica&shy;ção da verdade real. <br>
    O debate tem sido muito intenso,  face à casuística que chega à decisão da Justiça do Trabalho. Para  descaracteriza a relação empregatícia, na hipótese em exa&shy;me, é necessária a  comprovação do preenchimento dos seguintes requisitos: (a) serviços  especializados: (b) prestados sem pessoal idade ou subordinação direta; (c)  para atender à atividade-meio das empresas tomadoras.<br>
    As empresas tomadoras e as  fornecedoras de servi&shy;ços ou mão-de-obra devem Ter o máximo cuidado na eleição  de parceiros e celebração e execução dos res&shy;pectivos contratos, em razão dos  riscos a que estão sujeitas. </p>
<p class="first justify">Como já vimos, a terceirização é  possível em rela&shy;ção ao trabalho temporário e ao trabalho especializado  permanente. Esta última modalidade é legal, desde que o serviço seja prestado  por pessoa jurídica habilitada, sem pessoal idade ou subordinação direta e nas  hipóte&shy;ses legalmente contempladas. </p>
<p class="first justify">Com relação às obrigações  trabalhistas, em qual&shy;quer dessas hipóteses, é subsidiária a responsabilida&shy;de  das empresas tomadoras com as empresas forne&shy;cedoras de serviços ou  mão-de-obra. Conforme o Enun&shy;ciado nº 331 do TST, item IV, "o <em>inadimplemento  das obrigações trabalhistas, por parte do empregador, impli&shy;</em>ca <em>na  responsabilidade subsidiária do tomador dos ser&shy;viços quanto àquelas  obrigações, desde que este tenha participado da relação processual </em>e <em>conste do título exe&shy;cutivo judicial. </em>Não  distingue entre serviços terceirizados transitóri&shy;os ou especializados  permanentes. </p>
<p class="first justify">Quanto aos depósitos do Fundo de  Garantia do Tem&shy;po de Serviços, a solidariedade das empresas tomado&shy;ras com as  empresas fornecedoras de serviços decorre do artigo 15, § 1 º, da Lei nº 8.036, de 11 de maio de 1990, que dispõe sobre o FGTS,  e do artigo 2º, I, do Regulamento do FGTS, aprovado pelo Decreto nº 99.864, de  8 de novembro de 1990. Tais dispositivos legais consideram empregadores tanto a  empresa for&shy;necedora como a tomadora de serviços ou mão-de-obra que admitirem  trabalhadores a seu serviço.</p>
<p class="first justify">Com referência às obrigações  previdenciárias: (a) a Lei nº 8.212, de 24 de julho de 1991, que dispõe sobre a  organização da Seguridade Social e institui Plano de Custeio, no artigo 12,  inciso I, alínea b, e o Regulamen&shy;to da Organização e do Custeio da Seguridade  Social, aprovado pelo Decreto nº 356, de 7 de dezembro de 1991, com a nova  redação dada pelo Decreto nº 612, de 21 de julho de 1992, estabelece, nos  termos do artigo 10, inciso 1, alínea b, do aludido regulamento: </p>
<p class="first justify">"São segurados obrigatórios da  Previdência Social as seguintes pessoas físicas: 1 - como empregado: ((...) b) aquele que, contratado por empresa  de trabalho tem&shy;porário, por prazo não superior a três meses, prorrogá&shy;vel, presta serviço para atender a necessidade transitó&shy;ria de substituição  de pessoal regular e permanente ou a acréscimo extraordinário de serviço de  outras empre&shy;sas, na forma da legislação própria': (b) - a Ordem de Serviço nº  83, de 13 de agosto de 1993, DÁ de 17/ 09/93, e a Ordem de Serviço nº 87, de 20  de agosto de 1993, DOU de 17/09/93, do Diretor de Arrecadação e Fiscalização do  Instituto Nacional do Seguro Social &shy;INSS, prevêem a solidariedade das empresas  tomado&shy;ras com as empresas fornecedoras de serviços ou mão-de-obra”. </p>
<p class="first justify">Enfim, relativamente aos riscos, as  empresas toma&shy;doras e as empresas fornecedoras de serviços ou mão-de-obra têm  responsabilidade subsidiária, quanto ao FGTS e às contribuições previdenciárias  cabíeis.</p>
